///////////////////////////////////////////////////////////
//  Component.cs
//  Implementation of the Class Component
//  Generated by Enterprise Architect
//  Created on:      02-may.-2024 21:18:24
//  Original author: gaston
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class Acceso {

    public Guid	Id { get; set; }

	public string Nombre { get; set; }

    public Acceso(){

	}


	/// 
	/// <param name="component"></param>
	public abstract void Add(Acceso component);

	/// 
	/// <param name="component"></param>
	public abstract void Remove(Acceso component);

	public abstract int GetCount();

}//end Component