///////////////////////////////////////////////////////////
//  Leaf.cs
//  Implementation of the Class Leaf
//  Generated by Enterprise Architect
//  Created on:      02-may.-2024 21:18:24
//  Original author: gaston
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

public class Patente : Acceso {

    public TipoAcceso TipoAcceso { get; set; }

    public string DataKey { get; set; }

    public Patente(TipoAcceso tipoAcceso = TipoAcceso.UI){
		this.TipoAcceso = tipoAcceso;
	}

	/// 
	/// <param name="component"></param>
	public override void Add(Acceso component){

		throw new Exception("No se puede agregar un elemento");

	}

	/// 
	/// <param name="component"></param>
	public override void Remove(Acceso component){

        throw new Exception("No se puede quitar un elemento");

    }

    public override int GetCount()
    {
		return 0;
    }
}//end Leaf

public enum TipoAcceso
{
	UI,
	Control,
	UseCases
}