///////////////////////////////////////////////////////////
//  User.cs
//  Implementation of the Class User
//  Generated by Enterprise Architect
//  Created on:      02-may.-2024 21:18:24
//  Original author: gaston
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Usuario {

    public string UserName { get; set; }

    public string Password { get; set; }


    public List<Acceso> Accesos = new List<Acceso>();

	public Usuario(){

	}

    public List<Patente> GetPatentes()
    {
        return new List<Patente>();
    }

    public List<Familia> GetFamilias() {  

        return new List<Familia>(); 

    }

}//end User